-- ==========================================================
-- GROWFIT V1 SCHEMA (Migración Segura y No Destructiva)
-- ==========================================================

-- 1. PERFIL: Configuraciones generales (JSON)
CREATE TABLE IF NOT EXISTS public.profiles (
  user_id TEXT PRIMARY KEY,
  data JSONB
);

-- Asegurar columnas en caso de existencia previa
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS data JSONB;

-- 2. COMIDAS: Registro Diario - Tabla Relacional
CREATE TABLE IF NOT EXISTS public.meals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  date DATE NOT NULL,
  name TEXT,
  calories INT CHECK (calories >= 0),
  macros JSONB, -- { "protein": 30, "carbs": 50, "fat": 10 }
  icon TEXT,
  time TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Asegurar columnas en caso de existencia previa
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS calories INT;
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS macros JSONB;
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS icon TEXT;
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS time TEXT;
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_meals_user_date ON public.meals(user_id, date);

-- 3. MEDICIONES: Peso y Cuerpo
CREATE TABLE IF NOT EXISTS public.measurements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  date DATE NOT NULL,
  weight NUMERIC CHECK (weight > 0),
  neck NUMERIC CHECK (neck > 0 OR neck IS NULL),
  waist NUMERIC CHECK (waist > 0 OR waist IS NULL),
  hip NUMERIC CHECK (hip > 0 OR hip IS NULL),
  body_fat NUMERIC CHECK (body_fat >= 0),
  fat_mass NUMERIC,
  lean_mass NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Asegurar columnas en caso de existencia previa
ALTER TABLE public.measurements ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE public.measurements ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE public.measurements ADD COLUMN IF NOT EXISTS weight NUMERIC;
ALTER TABLE public.measurements ADD COLUMN IF NOT EXISTS neck NUMERIC;
ALTER TABLE public.measurements ADD COLUMN IF NOT EXISTS waist NUMERIC;
ALTER TABLE public.measurements ADD COLUMN IF NOT EXISTS hip NUMERIC;
ALTER TABLE public.measurements ADD COLUMN IF NOT EXISTS body_fat NUMERIC;
ALTER TABLE public.measurements ADD COLUMN IF NOT EXISTS fat_mass NUMERIC;
ALTER TABLE public.measurements ADD COLUMN IF NOT EXISTS lean_mass NUMERIC;
ALTER TABLE public.measurements ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_measurements_user_date ON public.measurements(user_id, date);

-- 4. ENTRENAMIENTOS
CREATE TABLE IF NOT EXISTS public.workouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  date DATE NOT NULL,
  type TEXT,
  duration INT CHECK (duration > 0),
  calories INT CHECK (calories >= 0),
  details JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Asegurar columnas en caso de existencia previa
ALTER TABLE public.workouts ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE public.workouts ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE public.workouts ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE public.workouts ADD COLUMN IF NOT EXISTS duration INT;
ALTER TABLE public.workouts ADD COLUMN IF NOT EXISTS calories INT;
ALTER TABLE public.workouts ADD COLUMN IF NOT EXISTS details JSONB;
ALTER TABLE public.workouts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_workouts_user_date ON public.workouts(user_id, date);

-- SEGURIDAD (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.measurements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workouts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Profiles" ON public.profiles;
CREATE POLICY "Public Profiles" ON public.profiles FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Meals" ON public.meals;
CREATE POLICY "Public Meals" ON public.meals FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Measurements" ON public.measurements;
CREATE POLICY "Public Measurements" ON public.measurements FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Workouts" ON public.workouts;
CREATE POLICY "Public Workouts" ON public.workouts FOR ALL USING (true) WITH CHECK (true);