-- INIT: Limpieza de tablas anteriores
drop table if exists user_data;
drop table if exists profiles;
drop table if exists meals;
drop table if exists measurements;
drop table if exists workouts;

-- 1. PERFIL: Configuraciones generales (JSON es eficiente aquí)
create table profiles (
  user_id text primary key,
  data jsonb
);

-- 2. COMIDAS (Registro Diario) - Tabla Relacional
create table meals (
  id bigint generated by default as identity primary key,
  user_id text not null,
  date date not null,
  name text,
  calories int,
  macros jsonb, -- { "protein": 30, "carbs": 50, "fat": 10 }
  icon text,
  time text,
  created_at timestamptz default now()
);

-- 3. MEDICIONES (Peso y Cuerpo)
create table measurements (
  id bigint generated by default as identity primary key,
  user_id text not null,
  date date not null,
  weight numeric,
  neck numeric,
  waist numeric,
  hip numeric,
  body_fat numeric,
  fat_mass numeric,
  lean_mass numeric,
  created_at timestamptz default now()
);

-- 4. ENTRENAMIENTOS
create table workouts (
  id bigint generated by default as identity primary key,
  user_id text not null,
  date date not null,
  type text,
  duration int,
  calories int,
  details jsonb,
  created_at timestamptz default now()
);

-- SEGURIDAD (Acceso Abierto para 'lucas-admin')
alter table profiles enable row level security;
alter table meals enable row level security;
alter table measurements enable row level security;
alter table workouts enable row level security;

create policy "Public Profiles" on profiles for all using (true) with check (true);
create policy "Public Meals" on meals for all using (true) with check (true);
create policy "Public Measurements" on measurements for all using (true) with check (true);
create policy "Public Workouts" on workouts for all using (true) with check (true);